#!/bin/bash
OUTPUT_DIR="/home/ripper/autorips/Bluray"
SOURCE_DRIVE="/dev/sr0"
HANDBRAKE_PRESET="AppleTV 3"
EXTENSION="mkv"
LOG_DIR="$OUTPUT_DIR/Logs"
function rip_bluray() {
        # We need to check to make sure our directories are sane
        if [ -d "$OUTPUT_DIR" ];
            then
            else
                mkdir -p $OUTPUT_DIR
        fi
        if [ -d "$LOG_DIR"];
            then
            else
                mkdir -p $LOGDIR
        fi
        # Grab the DVD title
        BLURAY_TITLE=$(blkid -o value -s LABEL $SOURCE_DRIVE)
        #Replace spaces with underscores
        BLURAY_TITLE=${BLURAY_TITLE// /_}
        # Backup the DVD to out hard drive
        makemkvcon backup --progress=$OUTPUT_DIR/$BLURAY_TITLE-MAKEMKV-PROGRESS.log disc:0 $OUTPUT_DIR/$BLURAY_TITLE --decrypt > $OUTPUT_DIR/$BLURAY_TITLE-MAKEMKV.log
        # HandBrake isn't ripping anything so we can pop out the disc
        eject $SOURCE_DRIVE
        # Cleanup Makemkv logs since they are no longer needed
        mv $OUTPUT_DIR/$BLURAY_TITLE-MAKEMKV* $LOGDIR/
        # grep for the HandBrakeCLI process and get the PID
        HANDBRAKE_PID=`ps aux|grep H\[a\]ndBrakeCLI`
        set -- $HANDBRAKE_PID
        HANDBRAKE_PID=$2
        # Wait until our previous Handbrake job is done
        if [ -n "$HANDBRAKE_PID" ]
        then
                while [ -e /proc/$HANDBRAKE_PID ]; do sleep 1; done
        fi
        # And now we can start encoding
        HandBrakeCLI -i $OUTPUT_DIR/$BLURAY_TITLE --main-feature -o $OUTPUT_DIR/$BLURAY_TITLE.$EXTENSION --preset=$HANDBRAKE_PRESET > $OUTPUT_DIR/$BLURAY_TITLE-HANDBRAKE.log
        # Clean up
        rm -R $OUTPUT_DIR/$BLURAY_TITLE
        # Cleanup Any left over log files
        mv $OUTPUT_DIR/$BLURAY_TITLE-* $LOGDIR/
}
rip_bluray
