#!/bin/bash
OUTPUT_DIR="/home/ripper/autorips/DVD"
SOURCE_DRIVE="/dev/sr0"
HANDBRAKE_PRESET="Normal"
EXTENSION="m4v"
LOG_DIR="$OUTPUT_DIR/Logs"
function rip_dvd() {
        # We need to check to make sure our directories are sane
        if [ -d "$OUTPUT_DIR" ];
            then
            echo "Output Directory Exists" &>> $OUTPUT_DIR/$DVD_TITLE-DVDBACKUP.log
            else
                mkdir -p $OUTPUT_DIR
        fi
        if [ -d "$LOG_DIR"];
            then
            echo "Log Directory Exists" &>> $OUTPUT_DIR/$DVD_TITLE-DVDBACKUP.log
            else
                mkdir -p $LOGDIR
        fi
        # Grab the DVD title
        DVD_TITLE=$(blkid -o value -s LABEL $SOURCE_DRIVE)
        # Replace spaces with underscores
        DVD_TITLE=${DVD_TITLE// /_}
        # Backup the DVD to out hard drive
        dvdbackup -i $SOURCE_DRIVE -o $OUTPUT_DIR -M -n $DVD_TITLE > $OUTPUT_DIR/$DVD_TITLE-DVDBACKUP.log
        # HandBrake isn't ripping anything so we can pop out the disc
        eject $SOURCE_DRIVE
        # Cleanup dvdbackup logs since they are no longer needed
        mv $OUTPUT_DIR/$DVD_TITLE-DVDBACKUP* $LOGDIR/
        # grep for the HandBrakeCLI process and get the PID
        HANDBRAKE_PID=`ps aux|grep H\[a\]ndBrakeCLI`
        set -- $HANDBRAKE_PID
        HANDBRAKE_PID=$2
        # Wait until our previous Handbrake job is done
        if [ -n "$HANDBRAKE_PID" ]
        then
                while [ -e /proc/$HANDBRAKE_PID ]; do sleep 1; done
        fi
        # And now we can start encoding
        HandBrakeCLI -i $OUTPUT_DIR/$DVD_TITLE --main-feature -o $OUTPUT_DIR/$DVD_TITLE.$EXTENSION --preset=$HANDBRAKE_PRESET > $OUTPUT_DIR/$DVD_TITLE-HANDBRAKE.log
        # Clean up
        rm -R $OUTPUT_DIR/$DVD_TITLE
        # Cleanup Any left over log files
        mv $OUTPUT_DIR/$DVD_TITLE-* $LOG_DIR/
}
rip_dvd
